# Generated by Django 3.0.5 on 2020-04-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_content_file_image_text_video'),
        ('accounts', '0002_user_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(related_name='participants', to='courses.Subject'),
        ),
    ]
