# Generated by Django 3.0.5 on 2020-04-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_subject_access_key'),
        ('accounts', '0004_auto_20200409_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='participants', to='courses.Subject'),
        ),
    ]
