# Generated by Django 3.1 on 2020-08-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_membership'),
        ('accounts', '0004_auto_20200808_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='enrolled_courses',
        ),
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='participants', through='courses.Membership', to='courses.Course'),
        ),
    ]
