# Generated by Django 3.1 on 2020-08-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200808_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name="User",
            name="courses"
        ),
        migrations.AddField(
            model_name="User",
            name="courses",
            field=models.ManyToManyField(blank=True, related_name='participants', through='courses.Membership', to='courses.Course'),
        )
    ]
