# Generated by Django 3.1 on 2020-08-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
