# Generated by Django 3.1 on 2020-08-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_auto_20200817_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='color',
            field=models.CharField(blank=True, default='#2222dd', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
