# Generated by Django 3.1 on 2020-08-18 13:55

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_auto_20200818_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="date",
        ),
        
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.DateField(default=datetime.datetime.now()),
        )
    ]
