# Generated by Django 3.1 on 2020-08-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0008_auto_20200821_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarsharetoken',
            name='token',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
