# Generated by Django 3.1 on 2020-08-21 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0009_auto_20200821_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarsharetoken',
            name='calendar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_token', to='cal.calendar'),
        ),
    ]
