# Generated by Django 3.1 on 2020-08-28 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0002_auto_20200808_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-updated']},
        ),
    ]
