# Generated by Django 3.1.7 on 2021-03-05 15:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_auto_20210228_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseadmin',
            old_name='can_add_content',
            new_name='can_edit_content',
        ),
        migrations.RenameField(
            model_name='courseadmin',
            old_name='can_add_participants',
            new_name='can_edit_participants',
        ),
        migrations.AlterUniqueTogether(
            name='courseadmin',
            unique_together={('user', 'course')},
        ),
        migrations.RemoveField(
            model_name='courseadmin',
            name='can_remove_content',
        ),
        migrations.RemoveField(
            model_name='courseadmin',
            name='can_remove_participants',
        ),
    ]
