# Generated by Django 3.0.5 on 2020-04-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_content_file_image_text_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='access_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
