# Generated by Django 3.1 on 2020-08-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200808_1509'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='membership',
            table=None,
        ),
    ]
