# Generated by Django 3.1.7 on 2021-03-08 10:14

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210306_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseadmin',
            options={'ordering': ['user__full_name']},
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Dev\\Django\\high_school\\static_my_proj_cdn\\protected'), upload_to='files'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Dev\\Django\\high_school\\static_my_proj_cdn\\protected'), upload_to='images'),
        ),
    ]
