# Generated by Django 3.1.7 on 2021-03-15 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semestr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('w', 'Winter'), ('s', 'Summer')], max_length=20)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentRecordBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('year', models.CharField(max_length=10)),
                ('repeated', models.BooleanField(default=False)),
                ('semestr', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gradebook.semestr')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='record_books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject_code', models.CharField(max_length=20)),
                ('ects_points', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubjectRecordBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('semestr', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gradebook.semestr')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='record_books', to='gradebook.subject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubjectRecordBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('is_open', models.BooleanField(default=True)),
                ('close_date', models.DateTimeField()),
                ('student_record_book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subjects_record_books', to='gradebook.studentrecordbook')),
                ('subject_record_book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='students_record_books', to='gradebook.subjectrecordbook')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('weight', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('o', 'Ordinar'), ('f', 'Final')], max_length=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('student_subject_record_book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gradebook.studentsubjectrecordbook')),
            ],
        ),
    ]
