# Generated by Django 3.1.7 on 2021-03-15 12:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0002_studentsubjectrecordbook_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecordbook',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 15, 12, 5, 7, 28364, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectrecordbook',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 15, 12, 5, 15, 448080, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
