# Generated by Django 3.1.7 on 2021-03-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0003_auto_20210315_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentrecordbook',
            options={'get_latest_by': 'created'},
        ),
        migrations.RemoveField(
            model_name='studentrecordbook',
            name='year',
        ),
        migrations.AlterField(
            model_name='subjectrecordbook',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
