# Generated by Django 3.1.7 on 2021-03-15 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0005_remove_studentsubjectrecordbook_close_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentrecordbook',
            options={'get_latest_by': 'semestr__start'},
        ),
        migrations.AlterField(
            model_name='grade',
            name='student_subject_record_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='grades', to='gradebook.studentsubjectrecordbook'),
        ),
    ]
