# Generated by Django 3.1.7 on 2021-03-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0006_auto_20210315_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubjectrecordbook',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
