# Generated by Django 3.1.7 on 2021-03-15 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0007_studentsubjectrecordbook_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='type',
        ),
    ]
