# Generated by Django 3.1.7 on 2021-03-16 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0008_remove_grade_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubjectrecordbook',
            name='final_grade_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_grade_1_for', to='gradebook.grade'),
        ),
        migrations.AddField(
            model_name='studentsubjectrecordbook',
            name='final_grade_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_grade_2_for', to='gradebook.grade'),
        ),
        migrations.AddField(
            model_name='studentsubjectrecordbook',
            name='final_grade_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_grade_3_for', to='gradebook.grade'),
        ),
    ]
